export const MerchantValidationCheck = [
  {
    selector: "textfield",
    label: "Phone Number",
    type: "number",
    placeholder: "Enter Number",
    name: "merchPhoneNo",
    isOnlyNumber: true,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Please select MNO",
    type: "text",
    placeholder: "Please Select",
    name: "merchantMNO",
    disabled: false,
  },
];

export const MerchantDetails = [
  {
    selector: "textfield",
    label: "Merchant Name",
    type: "text",
    placeholder: "",
    name: "merchantName",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "textfield",
    label: "Email",
    type: "email",
    placeholder: "",
    name: "merchantEmail",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Select Merchant Category",
    type: "select",
    placeholder: "Please Select",
    name: "merchantCategory",
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Gender",
    type: "select",
    placeholder: "Please Select",
    name: "merchantGender",
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Select Merchant Type",
    type: "select",
    placeholder: "Please Select",
    name: "merchantType",
    disabled: false,
  },
  {
    selector: "textfield",
    label: "Organisation Name",
    type: "text",
    placeholder: "",
    name: "merchantOrgName",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Organisation Type",
    type: "select",
    placeholder: "Please Select",
    name: "merchantOrgType",
    disabled: false,
  },
  {
    selector: "textfield",
    label: "Organisation Address",
    type: "text",
    placeholder: "",
    name: "merchantOrgAddress",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Type or Select Village/Area",
    type: "select",
    placeholder: "Please Select",
    name: "merchantVillageArea",
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Type or Select Thana/Upazila",
    type: "select",
    placeholder: "Please Select",
    name: "merchantThanaUpazila",
    disabled: false,
  },
  {
    selector: "dropdown",
    label: "Type or Select Division",
    type: "select",
    placeholder: "Please Select",
    name: "merchantDivision",
    disabled: false,
  },
  {
    selector: "textfield",
    label: "Post Office",
    type: "text",
    placeholder: "",
    name: "merchantPostOffice",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
  {
    selector: "textfield",
    label: "Post Code",
    type: "text",
    placeholder: "",
    name: "merchantPostCode",
    isOnlyNumber: false,
    isReadOnly: false,
    disabled: false,
  },
];
